const styles = {
  pageContainer: {
    fontFamily: "'Poppins', sans-serif",
    backgroundColor: "#fff5f8",
    minHeight: "100vh",
    overflow: "hidden",
  },
  bannerContainer: {
    display: "flex",
    alignItems: "stretch",
    justifyContent: "center",
    width: "100vw",
    height: "300px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.1)",
    marginBottom: "30px",
    borderRadius: "0 0 20px 20px",
    overflow: "hidden",
  },
  bannerImage: {
    width: "33.3%",
    objectFit: "cover",
  },
  bannerText: {
    fontSize: "24px",
    fontWeight: "bold",
    fontFamily: "'Pacifico', cursive",
    color: "#5a2d82",
    background: "linear-gradient(135deg, #ffe8f5 0%, #ffd1e8 100%)",
    textAlign: "center",
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 20px",
    textShadow: "1px 1px 2px rgba(255, 255, 255, 0.8)",
  },
  sectionContainer: {
    padding: "10px 20px",
    marginBottom: "30px",
    position: "relative",
  },
  categoriesContainer: {
    display: "flex",
    justifyContent: "center",
    gap: "35px",
    padding: "20px",
    marginBottom: "20px",
    position: "relative",
  },
  categoryItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    textDecoration: "none",
    color: "#5a2d82",
    transition: "transform 0.3s ease",
  },
  categoryImageContainer: {
    borderRadius: "50%",
    overflow: "hidden",
    width: "140px",
    height: "140px",
    boxShadow: "0 4px 10px rgba(0, 0, 0, 0.15)",
    border: "3px solid #fff",
    transition: "all 0.3s ease",
    background: "#fff",
  },
  categoryImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    transition: "transform 0.5s ease",
  },
  categoryText: {
    marginTop: "12px",
    fontSize: "16px",
    fontWeight: "bold",
    fontFamily: "Poppins, sans-serif",
    color: "#5a2d82",
    position: "relative",
    padding: "5px 0",
  },
  sectionTitle: {
    textAlign: "left",
    fontSize: "24px",
    fontWeight: "bold",
    fontFamily: "'Pacifico', cursive",
    marginTop: "30px",
    marginLeft: "30px",
    marginBottom: "20px",
    color: "#5a2d82",
    borderBottom: "2px solid #eba4c6",
    paddingBottom: "8px",
    display: "inline-block",
    position: "relative",
  },
  lanzamientosContainer: {
    display: "flex",
    justifyContent: "center",
    gap: "30px",
    padding: "20px",
    flexWrap: "wrap",
    position: "relative",
  },
  lanzamientoItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    width: "200px",
    transition: "all 0.3s ease",
    position: "relative",
  },
  lanzamientoImageContainer: {
    borderRadius: "15px",
    overflow: "hidden",
    boxShadow: "0 6px 15px rgba(0, 0, 0, 0.1)",
    width: "100%",
    height: "180px",
    position: "relative",
  },
  lanzamientoText: {
    marginTop: '12px',
    fontSize: '16px',
    fontWeight: 'bold',
    color: "#5a2d82",
    position: "relative",
  },
  lanzamientoImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    transition: "transform 0.5s ease",
  },
  lanzamientoInfo: {
    padding: "10px 0",
    width: "100%",
    textAlign: "left",
  },
  lanzamientoName: {
    fontSize: "16px",
    fontWeight: "bold",
    color: "#5a2d82",
    display: "block",
    marginBottom: "5px",
  },
  lanzamientoDetails: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: "5px",
  },
  lanzamientoPrice: {
    fontWeight: "bold",
    color: "#5a2d82",
    fontSize: "16px",
  },
  smallButton: {
    background: "none",
    border: "none",
    fontSize: "20px",
    cursor: "pointer",
    transition: "transform 0.2s ease",
  },
  newBadge: {
    position: "absolute",
    top: "10px",
    left: "10px",
    backgroundColor: "#ff69b4",
    color: "white",
    padding: "3px 10px",
    borderRadius: "12px",
    fontSize: "12px",
    fontWeight: "bold",
    boxShadow: "0 2px 5px rgba(0,0,0,0.2)",
    zIndex: "2",
  },
  setsContainer: {
    display: "flex",
    justifyContent: "center",
    gap: "25px",
    padding: "20px",
    flexWrap: "wrap",
  },
  card: {
    width: "240px",
    border: "none",
    borderRadius: "20px",
    textAlign: "center",
    backgroundColor: "#fff",
    padding: "15px",
    boxShadow: "0 10px 20px rgba(0, 0, 0, 0.08)",
    transition: "all 0.3s ease",
    position: "relative",
    overflow: "hidden",
  },
  imageContainer: {
    position: "relative",
    borderRadius: "15px",
    overflow: "hidden",
    boxShadow: "0 6px 12px rgba(0, 0, 0, 0.08)",
    zIndex: "1",
  },
  setImage: {
    width: "100%",
    height: "180px",
    objectFit: "cover",
    transition: "transform 0.5s ease",
  },
  favoriteIcon: {
    position: "absolute",
    top: "10px",
    right: "10px",
    fontSize: "24px",
    cursor: "pointer",
    filter: "drop-shadow(0 0 2px white)",
    zIndex: "2",
  },
  favoriteIconEmpty: {
    position: "absolute",
    top: "10px",
    right: "10px",
    fontSize: "24px",
    cursor: "pointer",
    filter: "drop-shadow(0 0 2px white)",
    zIndex: "2",
    transition: "transform 0.3s ease",
  },
  premiumCardBadge: {
    position: "absolute",
    bottom: "10px",
    right: "10px",
    backgroundColor: "#FFD700",
    color: "#5a2d82",
    padding: "3px 10px",
    borderRadius: "12px",
    fontSize: "12px",
    fontWeight: "bold",
    boxShadow: "0 2px 5px rgba(0,0,0,0.2)",
    zIndex: "2",
  },
  setTitle: {
    fontSize: "18px",
    fontWeight: "bold",
    marginTop: "15px",
    textAlign: "left",
    color: "#5a2d82",
    position: "relative",
    zIndex: "1",
  },
  setPrice: {
    fontSize: "18px",
    fontWeight: "bold",
    color: "#ff69b4",
    textAlign: "left",
    marginTop: "5px",
  },
  setDescription: {
    fontSize: "14px",
    color: "#666",
    marginTop: "8px",
    textAlign: "left",
    display: "block",
    lineHeight: "1.4",
    zIndex: "1",
    position: "relative",
  },
  actionContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: "15px",
    zIndex: "1",
    position: "relative",
  },
  viewMoreLink: {
    color: "#5a2d82",
    textDecoration: "none",
    fontWeight: "bold",
    fontSize: "14px",
    padding: "8px 12px",
    borderRadius: "20px",
    border: "1px solid #5a2d82",
    transition: "all 0.3s ease",
    background: "transparent",
    position: "relative",
    overflow: "hidden",
  },
  addToCartButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eba4c6",
    color: "white",
    border: "none",
    padding: "8px 12px",
    borderRadius: "20px",
    cursor: "pointer",
    fontWeight: "bold",
    transition: "all 0.3s ease",
    position: "relative",
    overflow: "hidden",
  },
  cartIcon: {
    marginRight: "5px",
    position: "relative",
    zIndex: "1",
  },
  
  // Estilos para la sección de colección del mes
  collectionBanner: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: "20px",
    overflow: "hidden",
    boxShadow: "0 10px 25px rgba(0,0,0,0.08)",
    margin: "20px 0",
    flexWrap: "wrap",
  },
  collectionInfo: {
    flex: "1",
    padding: "30px",
    minWidth: "300px",
  },
  collectionTitle: {
    fontSize: "24px",
    fontWeight: "bold",
    color: "#5a2d82",
    marginBottom: "15px",
  },
  collectionDescription: {
    fontSize: "16px",
    color: "#666",
    lineHeight: "1.6",
    marginBottom: "20px",
  },
  collectionButton: {
    display: "inline-block",
    backgroundColor: "#5a2d82",
    color: "white",
    padding: "12px 25px",
    borderRadius: "30px",
    textDecoration: "none",
    fontWeight: "bold",
    boxShadow: "0 5px 15px rgba(90,45,130,0.3)",
    transition: "transform 0.3s ease, box-shadow 0.3s ease",
  },
  collectionImageContainer: {
    flex: "1",
    minWidth: "300px",
    height: "350px",
    position: "relative",
    overflow: "hidden",
  },
  collectionImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    transition: "transform 0.5s ease",
  },
  
  // Estilos para la sección de testimonios
  testimoniosContainer: {
    display: "flex",
    justifyContent: "space-between",
    gap: "20px",
    flexWrap: "wrap",
    margin: "20px 0",
  },
  testimonioCard: {
    flex: "1",
    minWidth: "280px",
    backgroundColor: "#fff",
    borderRadius: "15px",
    padding: "25px",
    boxShadow: "0 5px 15px rgba(0,0,0,0.05)",
    transition: "transform 0.3s ease, box-shadow 0.3s ease",
  },
  testimonioText: {
    fontSize: "16px",
    color: "#666",
    lineHeight: "1.6",
    fontStyle: "italic",
    marginBottom: "15px",
    position: "relative",
    paddingLeft: "20px",
  },
  testimonioAuthor: {
    fontSize: "16px",
    fontWeight: "bold",
    color: "#5a2d82",
    marginBottom: "5px",
  },
  testimonioStars: {
    color: "#FFD700",
    fontSize: "16px",
  },
  
  // Estilos para la sección de preguntas frecuentes
  faqContainer: {
    margin: "20px 0",
  },
  faqItem: {
    backgroundColor: "#fff",
    borderRadius: "15px",
    padding: "20px",
    marginBottom: "15px",
    boxShadow: "0 5px 15px rgba(0,0,0,0.05)",
    transition: "transform 0.3s ease",
  },
  faqQuestion: {
    fontSize: "18px",
    fontWeight: "bold",
    color: "#5a2d82",
    marginBottom: "10px",
    position: "relative",
    paddingLeft: "25px",
  },
  faqAnswer: {
    fontSize: "16px",
    color: "#666",
    lineHeight: "1.6",
    paddingLeft: "25px",
    position: "relative",
  },
  
  // Estilos para la sección de llamado a la acción
  ctaContainer: {
    backgroundColor: "#f9f5f7",
    borderRadius: "20px",
    padding: "40px",
    margin: "40px 0",
    textAlign: "center",
    boxShadow: "0 10px 25px rgba(0,0,0,0.05)",
    background: "linear-gradient(135deg, #fff0f5 0%, #f9f5f7 100%)",
  },
  ctaTitle: {
    fontSize: "28px",
    fontWeight: "bold",
    color: "#5a2d82",
    marginBottom: "15px",
  },
  ctaText: {
    fontSize: "16px",
    color: "#666",
    maxWidth: "700px",
    margin: "0 auto 25px",
    lineHeight: "1.6",
  },
  subscribeContainer: {
    display: "flex",
    maxWidth: "500px",
    margin: "0 auto",
    flexWrap: "wrap",
    gap: "10px",
    justifyContent: "center",
  },
  subscribeInput: {
    flex: "1",
    minWidth: "250px",
    padding: "12px 20px",
    borderRadius: "30px",
    border: "1px solid #ddd",
    fontSize: "16px",
    outline: "none",
  },
  subscribeButton: {
    backgroundColor: "#5a2d82",
    color: "white",
    border: "none",
    padding: "12px 25px",
    borderRadius: "30px",
    fontSize: "16px",
    fontWeight: "bold",
    cursor: "pointer",
    boxShadow: "0 5px 15px rgba(90,45,130,0.3)",
    transition: "transform 0.3s ease, background-color 0.3s ease",
  },
  
  // Estilos para la sección de beneficios
  benefitsContainer: {
    display: "flex",
    justifyContent: "space-around",
    flexWrap: "wrap",
    gap: "20px",
    margin: "40px 0",
    padding: "20px 0",
    borderTop: "1px solid #f0e0e6",
    borderBottom: "1px solid #f0e0e6",
  },
  benefitItem: {
    flex: "1",
    minWidth: "200px",
    maxWidth: "250px",
    textAlign: "center",
    padding: "20px",
    transition: "transform 0.3s ease",
  },
  benefitIcon: {
    fontSize: "40px",
    marginBottom: "15px",
  },
  benefitTitle: {
    fontSize: "18px",
    fontWeight: "bold",
    color: "#5a2d82",
    marginBottom: "8px",
  },
  benefitText: {
    fontSize: "14px",
    color: "#666",
  },
    // Estilos para el carrusel de ofertas
      ofertasScrollContainer: {
        position: "relative",
        width: "100%",
        marginBottom: "20px",
      },
      ofertasCarousel: {
        display: "flex",
        overflowX: "auto",
        scrollBehavior: "smooth",
        padding: "10px 0 20px 0",
        WebkitOverflowScrolling: "touch", // Para mejor desempeño en iOS
        msOverflowStyle: "none", // Para IE y Edge
        scrollbarWidth: "none", // Para Firefox
        "&::-webkit-scrollbar": {
          display: "none", // Para Chrome, Safari y Opera
        },
      },
      ofertaCard: {
        flex: "0 0 auto",
        width: "280px",
        marginRight: "20px",
        backgroundColor: "#fff",
        borderRadius: "15px",
        boxShadow: "0 4px 15px rgba(0, 0, 0, 0.1)",
        padding: "15px",
        transition: "transform 0.3s ease, box-shadow 0.3s ease",
        "&:hover": {
          transform: "translateY(-5px)",
          boxShadow: "0 10px 25px rgba(0, 0, 0, 0.15)",
        },
      },
      ofertaImageContainer: {
        position: "relative",
        width: "100%",
        height: "200px",
        borderRadius: "10px",
        overflow: "hidden",
        marginBottom: "15px",
      },
      ofertaImage: {
        width: "100%",
        height: "100%",
        objectFit: "cover",
        transition: "transform 0.5s ease",
        "&:hover": {
          transform: "scale(1.05)",
        },
      },
      ofertaTitle: {
        fontSize: "18px",
        fontWeight: "bold",
        color: "#5a2d82",
        marginBottom: "8px",
      },
      ofertaDescription: {
        fontSize: "14px",
        color: "#666",
        marginBottom: "15px",
        height: "60px",
        overflow: "hidden",
      },
      limitedBadge: {
        position: "absolute",
        top: "10px",
        right: "10px",
        backgroundColor: "#ff9800",
        color: "white",
        padding: "3px 10px",
        borderRadius: "12px",
        fontSize: "12px",
        fontWeight: "bold",
        boxShadow: "0 2px 5px rgba(0,0,0,0.2)",
        zIndex: "2",
      },
      scrollIndicator: {
        textAlign: "center",
        color: "#888",
        fontSize: "14px",
        marginTop: "10px",
        fontStyle: "italic",
      },
    discountBadge: {
      position: "absolute",
      top: "10px",
      left: "10px",
      backgroundColor: "#ff4757",
      color: "white",
      padding: "3px 10px",
      borderRadius: "12px",
      fontSize: "12px",
      fontWeight: "bold",
      boxShadow: "0 2px 5px rgba(0,0,0,0.2)",
      zIndex: "2",
    },
    priceContainer: {
      display: "flex",
      alignItems: "center",
      gap: "10px",
      textAlign: "left",
      marginTop: "5px",
    },
    oldPrice: {
      fontSize: "14px",
      color: "#999",
      textDecoration: "line-through",
    },
    allSetsContainer: {
      padding: "20px",
      textAlign: "center",
    },
    comingSoonText: {
      fontSize: "18px",
      color: "#5a2d82",
      fontStyle: "italic",
    },

// Estilos para notificaciones
  notificacionExito: {
    position: "fixed",
    top: "20px",
    right: "20px",
    zIndex: 1000,
    backgroundColor: "#f8f0f4",
    borderLeft: "4px solid #ff6b9d",
    borderRadius: "4px",
    boxShadow: "0 4px 12px rgba(0,0,0,0.15)",
    padding: "12px 20px",
    minWidth: "280px",
    animation: "slideIn 0.3s ease-out forwards",
  },
  notificacionInfo: {
    position: "fixed",
    top: "20px",
    right: "20px",
    zIndex: 1000,
    backgroundColor: "#f0f4f8",
    borderLeft: "4px solid #6b9dff",
    borderRadius: "4px",
    boxShadow: "0 4px 12px rgba(0,0,0,0.15)",
    padding: "12px 20px",
    minWidth: "280px",
    animation: "slideIn 0.3s ease-out forwards",
  },
  notificacionContenido: {
    display: "flex",
    alignItems: "center",
    position: "relative",
  },
  notificacionIcono: {
    marginRight: "12px",
    fontSize: "20px",
  },
  notificacionMensaje: {
    fontSize: "14px",
    color: "#333",
    flex: 1,
  },
  notificacionCerrar: {
    background: "none",
    border: "none",
    color: "#999",
    fontSize: "16px",
    cursor: "pointer",
    padding: "0 5px",
    marginLeft: "10px",
    "&:hover": {
      color: "#333",
    },
  },
  // Estilos para iconos de favoritos
  favoriteIconSmall: {
    position: "absolute",
    top: "10px",
    right: "10px",
    fontSize: "18px",
    cursor: "pointer",
    zIndex: 3,
    filter: "drop-shadow(0 0 2px rgba(255,255,255,0.5))",
  },
  favoriteIconEmptySmall: {
    position: "absolute",
    top: "10px",
    right: "10px",
    fontSize: "18px",
    cursor: "pointer",
    zIndex: 3,
    filter: "drop-shadow(0 0 2px rgba(255,255,255,0.5))",
    transition: "transform 0.2s ease",
    "&:hover": {
      transform: "scale(1.2)",
    },
  },
// Estilos para el modal del carrito
  modalCarrito: {
    position: "fixed",
    top: "20px",
    right: "20px",
    zIndex: 1000,
    backgroundColor: "#fff",
    borderRadius: "8px",
    boxShadow: "0 5px 20px rgba(0,0,0,0.2)",
    padding: "0",
    width: "320px",
    animation: "slideIn 0.3s ease-out forwards",
    overflow: "hidden",
  },
  modalCarritoContenido: {
    position: "relative",
    padding: "20px",
  },
  modalCarritoIcono: {
    backgroundColor: "#4CAF50",
    color: "white",
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "20px",
    marginBottom: "15px",
  },
  modalCarritoInfo: {
    marginBottom: "15px",
  },
  modalCarritoTitulo: {
    fontSize: "16px",
    fontWeight: "bold",
    color: "#333",
    marginBottom: "8px",
  },
  modalCarritoProducto: {
    fontSize: "14px",
    color: "#666",
    marginBottom: "5px",
  },
  modalCarritoPrecio: {
    fontSize: "16px",
    fontWeight: "bold",
    color: "#ff69b4",
  },
  modalCarritoBotones: {
    display: "flex",
    gap: "10px",
  },
  modalCarritoBotonSeguir: {
    flex: "1",
    padding: "8px 0",
    backgroundColor: "#f0f0f0",
    border: "none",
    borderRadius: "4px",
    fontSize: "13px",
    cursor: "pointer",
    transition: "background-color 0.2s",
    "&:hover": {
      backgroundColor: "#e0e0e0",
    },
  },
  modalCarritoBotonVerCarrito: {
    flex: "1",
    padding: "8px 0",
    backgroundColor: "#5a2d82",
    color: "white",
    border: "none",
    borderRadius: "4px",
    fontSize: "13px",
    cursor: "pointer",
    transition: "background-color 0.2s",
    "&:hover": {
      backgroundColor: "#4a2468",
    },
  },
  modalCarritoCerrar: {
    position: "absolute",
    top: "10px",
    right: "10px",
    background: "none",
    border: "none",
    color: "#999",
    fontSize: "16px",
    cursor: "pointer",
    padding: "0 5px",
    "&:hover": {
      color: "#333",
    },
  },
// Add these styles to your CatalogoStyles.js file

modalFavoritos: {
position: 'fixed',
top: 0,
left: 0,
width: '100%',
height: '100%',
backgroundColor: 'rgba(0, 0, 0, 0.7)',
display: 'flex',
justifyContent: 'center',
alignItems: 'center',
zIndex: 1000,
},
modalFavoritosContenido: {
backgroundColor: 'white',
borderRadius: '8px',
padding: '20px',
width: '90%',
maxWidth: '600px',
maxHeight: '80vh',
overflow: 'auto',
position: 'relative',
},
modalFavoritosTitulo: {
fontSize: '24px',
marginBottom: '20px',
textAlign: 'center',
color: '#ff6b6b',
},
modalFavoritosCerrar: {
position: 'absolute',
top: '10px',
right: '10px',
background: 'none',
border: 'none',
fontSize: '20px',
cursor: 'pointer',
},
favoritosContainer: {
display: 'flex',
flexDirection: 'column',
gap: '15px',
},
favoritoItem: {
display: 'flex',
alignItems: 'center',
padding: '10px',
borderRadius: '8px',
backgroundColor: '#f9f9f9',
boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
},
favoritoImagen: {
width: '80px',
height: '80px',
objectFit: 'cover',
borderRadius: '4px',
},
favoritoInfo: {
flex: 1,
marginLeft: '15px',
},
favoritoNombre: {
fontSize: '16px',
margin: '0 0 5px 0',
},
favoritoPrecio: {
fontSize: '18px',
fontWeight: 'bold',
color: '#ff6b6b',
margin: 0,
},
favoritoAcciones: {
display: 'flex',
gap: '10px',
},
favoritoBotonEliminar: {
background: 'none',
border: 'none',
fontSize: '20px',
cursor: 'pointer',
},
favoritoBotonAgregar: {
background: 'none',
border: 'none',
fontSize: '20px',
cursor: 'pointer',
},
emptyFavoritos: {
textAlign: 'center',
padding: '20px',
color: '#888',
fontSize: '16px',
}
};

export default styles;